// This file is auto-generated by Shork. Do not edit.
import type { z } from 'zod';
import type { schema } from './+page.js';

/**
 * The inferred type of the data object from your Zod schema.
 * This is used for type-safety and autocompletion in your editor.
 */
export type PageData = z.infer<typeof schema>;
