// This file is auto-generated by Shork. Do not edit.

/**
 * The type of the data object for this page.
 * Since no Zod schema was defined in `+page.js`, this is a generic type.
 */
export type PageData = Record<string, any>;
